<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Continue Shopping_button__effects</name>
   <tag></tag>
   <elementGuidId>0eb3b370-45ce-4f7d-8551-e2013c100dc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app-root']/div[2]/div[2]/div/div[2]/div/div/div[2]/div/div/a/div/button/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.button__effects</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4857ef53-be90-4785-bc4d-4ba447bcc8e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button__effects</value>
      <webElementGuid>fd7bd72f-06f1-44be-baf5-407b2b19c907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/div[2]/div[@class=&quot;hz-contain&quot;]/div[@class=&quot;myAccount-page&quot;]/div[@class=&quot;content&quot;]/div[1]/div[@class=&quot;wishlist&quot;]/div[@class=&quot;listing__card&quot;]/div[@class=&quot;empty&quot;]/div[@class=&quot;error-not-found&quot;]/a[1]/div[@class=&quot;button__container&quot;]/button[@class=&quot;button button--inverted&quot;]/div[@class=&quot;button__effects&quot;]</value>
      <webElementGuid>440f5ee3-1c56-4cdf-8d69-e3e37ce82f0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-root']/div[2]/div[2]/div/div[2]/div/div/div[2]/div/div/a/div/button/div</value>
      <webElementGuid>b81098a6-36dc-454d-a9b7-e6bc63c9e7cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>1ec8382b-4dd0-4c38-8fea-10039fa0f6bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
