<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_lastname</name>
   <tag></tag>
   <elementGuidId>3119581b-cf57-4403-b222-54e707c3ef2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='lastname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;lastname&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33b09658-839f-4550-8386-65b96e95c059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your last name</value>
      <webElementGuid>f9a8db15-fddc-452a-b1d5-8c5662347637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e07abe8-39ca-4aff-bd72-99226bf29cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastname</value>
      <webElementGuid>c33c45c8-31ec-4915-bab7-ccbbda22b4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/div[2]/div[@class=&quot;hz-contain&quot;]/div[@class=&quot;myAccount-page&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;myProfile__container&quot;]/div[@class=&quot;myProfile__sections&quot;]/div[@class=&quot;myProfile__generalInfo&quot;]/div[@class=&quot;generalInfo__container&quot;]/form[1]/div[@class=&quot;inputs&quot;]/div[@class=&quot;input-wrapper hz-mt-20&quot;]/input[1]</value>
      <webElementGuid>737b667c-269c-4b28-8906-3b686edc9892</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='lastname']</value>
      <webElementGuid>f19a1fc0-2a95-4a38-88c8-21bc7e17c704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-root']/div[2]/div[2]/div/div[2]/div/div[2]/div/div/form/div/div[2]/input</value>
      <webElementGuid>a395cd0f-8227-4ba5-91ea-980a4d9f8719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>9a50f1dc-fb5f-49ce-80fe-3c8e9908af31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter your last name' and @type = 'text' and @name = 'lastname']</value>
      <webElementGuid>efa63154-60c1-4cf4-b46e-3fd68be96a62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
