<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Password_confirmPassword</name>
   <tag></tag>
   <elementGuidId>9c62577b-c408-48d8-b765-20c9f839f9d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='confirmPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;confirmPassword&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8693c4a-5c93-47aa-95ed-caf592b16a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm Password</value>
      <webElementGuid>b4de3c81-b052-4486-bc0b-317ffbad5c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>20f9c536-23cd-46ff-99c5-59bdc058ae94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmPassword</value>
      <webElementGuid>fe0b991e-16a2-40cf-a291-dd00a20caa48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/div[2]/div[@class=&quot;hz-contain&quot;]/div[@class=&quot;myAccount-page&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;myProfile__container&quot;]/div[@class=&quot;myProfile__sections&quot;]/div[@class=&quot;myProfile__Security&quot;]/div[@class=&quot;security__container&quot;]/div[@class=&quot;modal_container&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;passwordForm__container&quot;]/form[1]/div[@class=&quot;input-wrapper hz-mt-20&quot;]/div[@class=&quot;password-wrapper&quot;]/input[1]</value>
      <webElementGuid>b1bb71df-8918-4b07-8e01-b5a6b51478f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='confirmPassword']</value>
      <webElementGuid>17124b56-deaa-4b91-b803-6d0c8721e244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-root']/div[2]/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div[2]/div/form/div[3]/div/input</value>
      <webElementGuid>62517e0d-0663-47b5-a3f3-e9d998e27597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>dc1017b7-64f9-46d3-9056-77c5f2a4ac71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Confirm Password' and @type = 'password' and @name = 'confirmPassword']</value>
      <webElementGuid>944851c3-0657-4849-89b0-871434609efb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
