<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_New Password_newPassword</name>
   <tag></tag>
   <elementGuidId>6772542e-a6f0-4891-9e35-d698b077b6ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='newPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;newPassword&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbbf5f21-ec07-4b23-9145-f6315537cdb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>New Password</value>
      <webElementGuid>836d4c76-8977-4bbd-a24f-1c6749700bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b5808128-3216-4500-8086-51c9e940207c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>newPassword</value>
      <webElementGuid>2021dd70-a027-441f-9cdf-0dce697fcd4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app-root&quot;)/div[2]/div[@class=&quot;hz-contain&quot;]/div[@class=&quot;myAccount-page&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;myProfile__container&quot;]/div[@class=&quot;myProfile__sections&quot;]/div[@class=&quot;myProfile__Security&quot;]/div[@class=&quot;security__container&quot;]/div[@class=&quot;modal_container&quot;]/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;passwordForm__container&quot;]/form[1]/div[@class=&quot;input-wrapper hz-mt-20&quot;]/div[@class=&quot;password-wrapper&quot;]/input[1]</value>
      <webElementGuid>b30f1e5c-0de9-4244-b961-a3578664d0a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='newPassword']</value>
      <webElementGuid>5090d6b5-f616-42c3-b358-d84ddf79e954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-root']/div[2]/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div[2]/div/form/div[2]/div/input</value>
      <webElementGuid>1d594899-28b7-46c2-8818-36d4395ed880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>37ee8dd1-40e9-4cf9-9310-d2a33bf1f35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'New Password' and @type = 'password' and @name = 'newPassword']</value>
      <webElementGuid>39f936b3-be7c-4d5a-94e1-39c7a87dbce3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
