<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add to cart_ProductDetails_wishList__r0L50</name>
   <tag></tag>
   <elementGuidId>31c92423-10a1-456a-bda4-3f08019638ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div/div/div[2]/div[5]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ProductDetails_wishList__r0L50</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c200117d-94e8-4a0f-8587-3be86d8776d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ProductDetails_wishList__r0L50</value>
      <webElementGuid>2506aca5-2166-456b-8df6-f0b54fd80882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;__className_818b7e&quot;]/div[2]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg base-container_baseContainer__W84Zx base-container_sm_p0__WNSf7 muiltr-1qsxih2&quot;]/div[@class=&quot;ProductDetails_detailsPage__rigKh&quot;]/div[@class=&quot;ProductDetails_sectionOne__Eu_BD&quot;]/div[@class=&quot;ProductDetails_product__details__gl63Y&quot;]/div[@class=&quot;ProductDetails_addToCart__qYYSD&quot;]/div[@class=&quot;ProductDetails_wishList__r0L50&quot;]</value>
      <webElementGuid>3c8ad504-65ac-4389-b702-dc1383abcbfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div/div[2]/div[5]/div[2]</value>
      <webElementGuid>355ef1a5-92f1-457a-93a4-d34a30a0a2f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[1]/following::div[1]</value>
      <webElementGuid>91afdb5c-fd75-4838-aa5c-b78347b67340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::div[3]</value>
      <webElementGuid>5a018b67-2a94-4d6d-9d1d-077a95740822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]</value>
      <webElementGuid>6e546c96-3963-4971-a353-b1c2908101c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div/div[2]/div[4]/div[2]</value>
      <webElementGuid>9e89e19e-a67c-45a8-810f-422c9e48c26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div[2]</value>
      <webElementGuid>06aa60c4-8290-4e04-8b86-103f8a338766</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
