<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_generate email</name>
   <tag></tag>
   <elementGuidId>343da64b-9a0e-4080-9350-7b40d31de71c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[2]/div/div/div/form/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.generateBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;generate email&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf70bcd8-3737-499c-9414-234ab923c155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>generateBtn</value>
      <webElementGuid>354bc247-d0af-46f1-887a-9dda1cb0ea95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>generate email </value>
      <webElementGuid>7f6e42a6-13d7-46bf-856a-df4842f4edd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;Registerstyled__RegisterContainer-sc-lixkwx-0 lmAjHi&quot;]/div[1]/div[@class=&quot;signUpPageContainer&quot;]/div[@class=&quot;subLoginPage&quot;]/form[1]/div[@class=&quot;flex-Center&quot;]/div[@class=&quot;generateBtn&quot;]</value>
      <webElementGuid>341f30ce-94c7-41bb-8a30-8199b1ec4f22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div/form/div/div</value>
      <webElementGuid>ff56631e-077f-4392-82d8-899d66fa6cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Join Twitter Today'])[1]/following::div[3]</value>
      <webElementGuid>26d67af9-6631-4123-9347-fa2255168eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='generate username'])[1]/preceding::div[1]</value>
      <webElementGuid>6b0aa214-52c5-4a55-aace-7f58935a34b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='generate password'])[1]/preceding::div[3]</value>
      <webElementGuid>d947ce84-d597-4911-ae80-d12afb1b8371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='generate email']/parent::*</value>
      <webElementGuid>19581df6-84aa-4fcf-8fe3-4c3fbb8b4497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>d245b226-dd23-414e-b66a-b304bb517108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'generate email ' or . = 'generate email ')]</value>
      <webElementGuid>be8c16e7-fc2e-4dc1-93af-27ea63c9e536</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
