<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SkipVerify your mobile numberHelp us se_bd29bd</name>
   <tag></tag>
   <elementGuidId>4d75012c-dc4e-4caf-914d-81b1e5ad9854</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.__className_818b7e</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5a6e0e0d-dc1a-411a-b618-6ca3ddeecfc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>__className_818b7e</value>
      <webElementGuid>cc58e899-a573-40f8-b052-40f19826a517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SkipVerify your mobile numberHelp us secure your account. Press “Send OTP“ to complete verification+20​change​Send OTPNeed Help</value>
      <webElementGuid>7b58f273-951e-4602-b5ac-f51eed596bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;__className_818b7e&quot;]</value>
      <webElementGuid>1e3c5360-89ca-4fb8-8df2-1c1d0a1a1d3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div</value>
      <webElementGuid>a2b96fe8-67c6-4fd8-ab6f-d9533285eb90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>f2c76c3f-0b57-45e5-bd37-a8d1c75f0e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'SkipVerify your mobile numberHelp us secure your account. Press “Send OTP“ to complete verification+20​change​Send OTPNeed Help' or . = 'SkipVerify your mobile numberHelp us secure your account. Press “Send OTP“ to complete verification+20​change​Send OTPNeed Help')]</value>
      <webElementGuid>b0d57dcb-62c0-433c-9a21-8d29f6c4a9a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>3855b232-0c2c-451c-a40d-055950bb68b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
