<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>2c010587-efd0-4e8f-b8a5-0a11dd621935</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/main/div/div/div/div[3]/div/div/div/div/div/div/div[5]/div[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Minus&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e777deb9-a02a-44c8-94bb-2c86fcafa205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Minus</value>
      <webElementGuid>332b7c3a-eb91-486c-b244-c8d1a95c9b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>cf914305-b813-4a55-82c2-4a4fc0936b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>96376ea9-393a-453f-ab7b-da824f18c161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>5e556624-7d09-4715-a107-8209e9425d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>670c07a2-03e8-4239-9fad-a1eefb657327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0c518076-0b3b-4165-a974-9df0c6ab524f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/static/media/cartMinus.f661f7f1.svg</value>
      <webElementGuid>7eaf0210-b156-4997-b958-34f88dbdfc14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;__className_818b7e&quot;]/div[@class=&quot;Cart_cartWrapper__b7TxU&quot;]/main[1]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg base-container_baseContainer__W84Zx base-container_sm_p0__WNSf7 muiltr-1qsxih2&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-2 muiltr-isbt42&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-8 muiltr-efwuvd&quot;]/div[@class=&quot;Cart_CartCard__container__TyOoP&quot;]/div[1]/div[1]/div[@class=&quot;Card_card__container__yOndH&quot;]/div[@class=&quot;Card_card__nuEQX&quot;]/div[@class=&quot;Card_cardWrapper__6McRX&quot;]/div[@class=&quot;Card_itemInfo__yCOcB&quot;]/div[@class=&quot;Card_card__actions__wrapper__jL0_f&quot;]/div[2]/div[@class=&quot;CardQty_CardQty__container__GJDG6&quot;]/div[1]/img[1]</value>
      <webElementGuid>0abcc8a5-7022-4702-8818-44537d572fc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/main/div/div/div/div[3]/div/div/div/div/div/div/div[5]/div[2]/div/div/img</value>
      <webElementGuid>373581dd-03f0-4ff7-847a-b7cf773d3d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Minus']</value>
      <webElementGuid>0974b389-c98a-420b-9509-5917328622c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>9c567124-ff0a-473f-994b-7c497e39fe85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Minus' and @src = '/_next/static/media/cartMinus.f661f7f1.svg']</value>
      <webElementGuid>6cf4d3c0-a853-40e9-9aa7-e814458f17c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='delet']</value>
      <webElementGuid>fc76fdad-54fb-4408-a209-f8e21976af9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'delet' and @src = '/_next/static/media/delete.02ed8469.svg']</value>
      <webElementGuid>3903edc8-d1ac-4eca-bfae-04690f6cebd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
