<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2</name>
   <tag></tag>
   <elementGuidId>092e282e-879f-4006-9f2e-965c52f010de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/main/div/div/div/div[3]/div/div/div/div/div/div/div[5]/div[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;delet&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>aeaa78c9-af70-4d87-abbc-78a87cf414c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>delet</value>
      <webElementGuid>c0915133-302f-4e83-a7d4-b378d7d4ed6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>10eb43ac-433d-4b56-b42b-534aa2df1668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>aa06f954-ee26-4aa4-8ca9-f67586ca63f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>77b94488-e596-45b1-90bf-a92e00870cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>f2681760-4f47-4414-b002-f0c313391ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>75d39f36-854c-4dd8-a2f6-0b3fcccc9816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/static/media/delete.02ed8469.svg</value>
      <webElementGuid>c319410e-2384-4302-ac30-9756435ae646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;__className_818b7e&quot;]/div[@class=&quot;Cart_cartWrapper__b7TxU&quot;]/main[1]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg base-container_baseContainer__W84Zx base-container_sm_p0__WNSf7 muiltr-1qsxih2&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-2 muiltr-isbt42&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-8 muiltr-efwuvd&quot;]/div[@class=&quot;Cart_CartCard__container__TyOoP&quot;]/div[1]/div[1]/div[@class=&quot;Card_card__container__yOndH&quot;]/div[@class=&quot;Card_card__nuEQX&quot;]/div[@class=&quot;Card_cardWrapper__6McRX&quot;]/div[@class=&quot;Card_itemInfo__yCOcB&quot;]/div[@class=&quot;Card_card__actions__wrapper__jL0_f&quot;]/div[2]/div[@class=&quot;CardQty_CardQty__container__GJDG6&quot;]/div[1]/img[1]</value>
      <webElementGuid>806ced5c-d70b-4338-8542-89c8e7b285e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/main/div/div/div/div[3]/div/div/div/div/div/div/div[5]/div[2]/div/div/img</value>
      <webElementGuid>39a3c120-167c-4d74-9c5d-1d5f2698fcf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='delet']</value>
      <webElementGuid>0e5ee7e8-26f5-44f1-b619-f08e0da90104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>b79d0156-8c07-4cd3-b701-f5402f529148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'delet' and @src = '/_next/static/media/delete.02ed8469.svg']</value>
      <webElementGuid>05f3fe82-7e35-4a91-a56f-45afe8c843b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
