<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Excluding official holidays and vacatio_f2668b</name>
   <tag></tag>
   <elementGuidId>6b5b66c1-1c6a-4e1a-879f-802214182f88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div/div/div[2]/div[6]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.ProductDetails_plus__wX7Ls</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dd729c85-bd9d-42ab-bd93-2be33bd9bda2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>add</value>
      <webElementGuid>c891c131-c4e3-4cb5-a001-b08eb972071a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>af14c543-bae3-4c6a-a1a1-7f39354c9835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>2b31d91e-af9f-44e3-9f09-8ea688a3eb1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>981facbb-576d-4c70-9a39-09e30a5d0f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>6cc6741d-624b-4bcb-b87d-67872d8609ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>41df583d-38de-49cd-aab6-60927585cd56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ProductDetails_plus__wX7Ls</value>
      <webElementGuid>ad8770e0-4a93-4824-beee-8aef246fe71a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/static/media/plus.b12243fc.svg</value>
      <webElementGuid>134212cd-c8a8-448f-8962-a5a5e1b80565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;__className_818b7e&quot;]/div[2]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg base-container_baseContainer__W84Zx base-container_sm_p0__WNSf7 muiltr-1qsxih2&quot;]/div[@class=&quot;ProductDetails_detailsPage__rigKh&quot;]/div[@class=&quot;ProductDetails_sectionOne__Eu_BD&quot;]/div[@class=&quot;ProductDetails_product__details__gl63Y&quot;]/div[@class=&quot;ProductDetails_addToCart__qYYSD&quot;]/div[@class=&quot;ProductDetails_addQty__oa5hX&quot;]/img[@class=&quot;ProductDetails_plus__wX7Ls&quot;]</value>
      <webElementGuid>0b539d17-cdbd-4d90-bb8e-ef9406376047</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div/div[2]/div[6]/div/img</value>
      <webElementGuid>d99b51be-c178-4889-9740-440d61904ff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='add']</value>
      <webElementGuid>1697d426-e51f-49c3-91ab-3840d0063d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/img</value>
      <webElementGuid>14c6647c-bc2b-4810-bfa0-25e19e412734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'add' and @src = '/_next/static/media/plus.b12243fc.svg']</value>
      <webElementGuid>adb20f82-6bea-40d3-be3f-cd0c29cfb19a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
