<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Confirm password</name>
   <tag></tag>
   <elementGuidId>54d4adea-4fc5-4fc6-abba-cd4422291bd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//label[@id='outlined-basic-label'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>31e05cc8-e2b9-4f42-9d22-a453adc854cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeMedium MuiInputLabel-outlined MuiFormLabel-colorPrimary Mui-focused MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeMedium MuiInputLabel-outlined muiltr-1974vn9</value>
      <webElementGuid>190009a5-3052-4a7e-99bb-ab056cc8baa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-shrink</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>45ea93d7-90d9-4765-a337-42d265080f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>outlined-basic</value>
      <webElementGuid>1d8ba49f-d344-4307-b7c1-55d807cd1ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>outlined-basic-label</value>
      <webElementGuid>4751ff7e-07ee-44a7-be30-54882449ebb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm password</value>
      <webElementGuid>7c4d0f80-7213-4b1a-be94-7eb6ca264585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;__className_818b7e&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg MuiContainer-fixed muiltr-x3h831&quot;]/div[@class=&quot;AccountMangmentLayout_accountMangment_container__u98U8&quot;]/div[@class=&quot;AccountMangmentLayout_centered_content__vkp9B HMZ_gap24&quot;]/div[@class=&quot;AccountMangmentLayout_children__16Gjr&quot;]/div[@class=&quot;Register_Register_container__3hWL4 HMZ_gap24&quot;]/form[@class=&quot;Register_LogIn_Form__wkFFd&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-item undefined HMZ_gap18 muiltr-1ul47bz&quot;]/div[@class=&quot;MuiFormControl-root MuiTextField-root base-password-input_BasePasswordInput__mMDxt muiltr-i44wyl&quot;]/label[@id=&quot;outlined-basic-label&quot;]</value>
      <webElementGuid>b0263dd7-2926-444b-8351-c4b713194ce6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//label[@id='outlined-basic-label'])[3]</value>
      <webElementGuid>2d76e86e-3aee-4e8f-88a6-f2b3856e6550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div[2]/div/form/div/div[5]/label</value>
      <webElementGuid>d3f54101-251c-4d20-8238-24257b1e054c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create password'])[2]/following::label[1]</value>
      <webElementGuid>9e7df542-0d07-4568-9e05-0e0b6f57c711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create password'])[1]/following::label[1]</value>
      <webElementGuid>071465bc-b815-43d3-b4ad-f04354e88988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm password'])[2]/preceding::label[1]</value>
      <webElementGuid>efc5f41e-6153-481f-b794-d45f5e49d6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Account'])[1]/preceding::label[1]</value>
      <webElementGuid>ae47a0f7-e0a7-4820-a7be-526ed0c20d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm password']/parent::*</value>
      <webElementGuid>e7afbd06-8d4b-45f5-89d2-106fedf0b32b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label</value>
      <webElementGuid>b8325325-4c38-43f3-8606-85501986ec28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'outlined-basic-label' and (text() = 'Confirm password' or . = 'Confirm password')]</value>
      <webElementGuid>ab002d15-2699-401f-a396-9e3699c98c23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
