<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Delete</name>
   <tag></tag>
   <elementGuidId>e42e95df-a78e-405a-b58f-c880550ebc4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[3]/main/div/div/div/div[3]/div/div/div/div/div/div/div[5]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.base-typography_p__HIGSb.base-typography_small__VvVHg.Card_detelte___qSI6.undefined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>p >> internal:has-text=/^Delete$/</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>045c1bb7-acee-4a81-bb88-2de42494afe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-typography_p__HIGSb base-typography_small__VvVHg Card_detelte___qSI6 undefined</value>
      <webElementGuid>c8a2ee27-5e26-4ca2-a44c-c4293de2689f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>a57ec8a3-6f8e-40b6-bfb1-16c2b89e7fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;__className_818b7e&quot;]/div[@class=&quot;Cart_cartWrapper__b7TxU&quot;]/main[1]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg base-container_baseContainer__W84Zx base-container_sm_p0__WNSf7 muiltr-1qsxih2&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-2 muiltr-isbt42&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-8 muiltr-efwuvd&quot;]/div[@class=&quot;Cart_CartCard__container__TyOoP&quot;]/div[1]/div[1]/div[@class=&quot;Card_card__container__yOndH&quot;]/div[@class=&quot;Card_card__nuEQX&quot;]/div[@class=&quot;Card_cardWrapper__6McRX&quot;]/div[@class=&quot;Card_itemInfo__yCOcB&quot;]/div[@class=&quot;Card_card__actions__wrapper__jL0_f&quot;]/div[@class=&quot;Card_card__actions__Z8_7c&quot;]/p[@class=&quot;base-typography_p__HIGSb base-typography_small__VvVHg Card_detelte___qSI6 undefined&quot;]</value>
      <webElementGuid>d134dc32-23b0-4dbe-aca1-e310a74d1cab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[3]/main/div/div/div/div[3]/div/div/div/div/div/div/div[5]/div/p</value>
      <webElementGuid>15a4a0f6-c97b-41e6-b2de-daa96571d1e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EGP'])[1]/following::p[4]</value>
      <webElementGuid>f618b5ef-8397-43f1-a458-035dcbf09cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart'])[3]/following::p[5]</value>
      <webElementGuid>421f1dca-164d-4e3f-9d14-56a7a51ca995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Delivery Location'])[2]/preceding::p[6]</value>
      <webElementGuid>f7eb04e6-b7f4-4563-8ff1-69c25854b547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coupon Code'])[1]/preceding::p[6]</value>
      <webElementGuid>b4035c2b-5587-49b1-9b57-6a85f3ecbb38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delete']/parent::*</value>
      <webElementGuid>80c7ddab-dfe1-45dd-93ca-c1251ede6d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/p</value>
      <webElementGuid>78bed9f6-13bd-4209-8c0a-f07a672e6bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>b3238209-c2c1-428c-9ee6-f45999b30930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EGP'])[2]/preceding::p[6]</value>
      <webElementGuid>e35723ed-29af-442d-8f0a-81827dd9e41e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
