<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_please Select RegionKafr el DawarDamnhou_7cb7f5</name>
   <tag></tag>
   <elementGuidId>962ba58e-b1f8-4a66-a4c2-603ca4117f3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id=':rg:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>66b6b149-24ae-4bfc-8af0-807f46bb496e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiList-root MuiList-padding MuiMenu-list muiltr-r8u8y9</value>
      <webElementGuid>0f9f38d1-a721-4751-8bd4-e39d099f6fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>9454a807-fa79-4642-a0a9-ac10e01dd9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5a988ee6-803d-4b74-befd-63ed9b1ad135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:rg:</value>
      <webElementGuid>ab9e15db-bedb-41ed-b5ed-00faa006d518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>please Select RegionKafr el DawarDamnhourItaia al Barud</value>
      <webElementGuid>8c260417-70e3-4740-9f4a-4d7a8ae00ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rg:&quot;)</value>
      <webElementGuid>18b5cdd5-86a3-4ead-9234-bc62862f3126</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id=':rg:']</value>
      <webElementGuid>f6cc4aeb-0461-4551-8591-919cb4691cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-city']/div[3]/ul</value>
      <webElementGuid>a896aa76-4e23-4f41-b223-bc0b71c3896f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/following::ul[1]</value>
      <webElementGuid>53131858-77ea-4b20-9b2a-45d0f9c815a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work'])[2]/following::ul[1]</value>
      <webElementGuid>6770ba9f-81a8-477e-960a-5c2289513eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul</value>
      <webElementGuid>258d14eb-b3ed-44ab-ac7d-6a2a7b193b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = ':rg:' and (text() = 'please Select RegionKafr el DawarDamnhourItaia al Barud' or . = 'please Select RegionKafr el DawarDamnhourItaia al Barud')]</value>
      <webElementGuid>0395a365-9ec1-4eb3-8c70-77b66ebac6a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
