<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_or use your email forregistration_aut_b0e888_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>0d9a12d9-fe6c-4216-b9b0-71e9491d729f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Test']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.auth-form__container.auth-form__sign-up > form.auth-form__form > input.auth-form__input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2ce2555-c168-46a2-b508-79c6cbaa35a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>auth-form__input</value>
      <webElementGuid>0607dc49-ddbf-4933-ac3f-b378862c1068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bbf150bc-f8b1-4c0d-a1c4-be0ce3198112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>a2313931-d2b2-4bec-a332-b8d9022a3ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Test</value>
      <webElementGuid>ae2f0af9-0c39-4013-b82a-7e7a1c40a792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;tv-navigation-root&quot;]/div[@class=&quot;auth-container&quot;]/div[@class=&quot;auth-form right-panel-active&quot;]/div[@class=&quot;auth-form__container auth-form__sign-up&quot;]/form[@class=&quot;auth-form__form&quot;]/input[@class=&quot;auth-form__input&quot;]</value>
      <webElementGuid>3a98069e-645c-436d-a745-e727fb2c1c2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Test']</value>
      <webElementGuid>72b15424-d4ae-49d8-92a2-75aa8724fe1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/form/input</value>
      <webElementGuid>2d15b878-aff7-4f94-a742-9671ce4f0a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/input</value>
      <webElementGuid>34cdc622-5b25-48b9-99cf-77a653d5f51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Name']</value>
      <webElementGuid>b3438ace-6faa-4f0f-a0e1-9402a20842fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
