<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_or use your email forregistration_aut_b0e888_1_2_3_4_5_6_7_8_9_10</name>
   <tag></tag>
   <elementGuidId>87fdd0d4-8077-4f2e-8034-b807fe7e4f33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='Test777@g'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>16b37106-7149-4f50-aab1-81bd656d9883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>auth-form__input</value>
      <webElementGuid>f52f01e6-e304-416a-a1d3-641e59eb58d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>cb6e5c56-edca-4368-9b80-17e2a823e60e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>f77f8a2b-8dab-4d84-99e2-8b2a8cbdfa01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Test777@g</value>
      <webElementGuid>309f5a1d-5c23-43bc-8650-c658087dcc92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;tv-navigation-root&quot;]/div[@class=&quot;auth-container&quot;]/div[@class=&quot;auth-form right-panel-active&quot;]/div[@class=&quot;auth-form__container auth-form__sign-up&quot;]/form[@class=&quot;auth-form__form&quot;]/input[@class=&quot;auth-form__input&quot;]</value>
      <webElementGuid>82b01a2b-d7e5-4d8c-bf9b-c215d745514e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='Test777@g'])[2]</value>
      <webElementGuid>430bc665-5e5f-4aa8-abc2-b7c4e45e2803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/form/input[2]</value>
      <webElementGuid>8c6f82e4-4848-4808-a5f1-412951ae5759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/input[2]</value>
      <webElementGuid>b5e2d14b-f760-44be-a452-7c0a6b28e841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @placeholder = 'Email']</value>
      <webElementGuid>d80ac749-220f-4993-bf84-1c14b22440cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
