<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_End-of-Year Clearance Get extra 15 discou_c35f65</name>
   <tag></tag>
   <elementGuidId>1646fd56-e816-4cb2-b2ec-f2754dd0d3e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;End-of-Year Clearance! Get extra 15% discount with code: EXTRA15&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d56d3825-8cf5-46ad-9adf-f381679f8f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://homzmart.com/en/c/top-selling</value>
      <webElementGuid>a53571e9-7998-422d-90eb-3ece956ee335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>End-of-Year Clearance! Get extra 15% discount with code: EXTRA15</value>
      <webElementGuid>1f33494b-0adb-4d58-97d2-30aafdc0e664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;__className_818b7e&quot;]/div[@class=&quot;MuiGrid-root muiltr-1ij0jnt&quot;]/div[@class=&quot;MuiGrid-root styles_headerContainer__zvolI muiltr-rfnosa&quot;]/div[@class=&quot;top-ticker_topTicker__container__8T3gR&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg base-container_baseContainer__W84Zx undefined muiltr-1qsxih2&quot;]/div[@class=&quot;hz-contain&quot;]/a[1]</value>
      <webElementGuid>7b684cd7-53be-456c-953c-ecb0fe4fbfbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div/a</value>
      <webElementGuid>781d53da-368e-4586-b20c-fab31290709f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'End-of-Year Clearance! Get extra 15% discount with code: EXTRA15')]</value>
      <webElementGuid>c4cd07a7-5dcf-42a9-af43-20f4c43dc3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deliver to'])[1]/preceding::a[2]</value>
      <webElementGuid>7da0d511-7cd7-453d-8562-750e3f7ceb47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/preceding::a[2]</value>
      <webElementGuid>a9702784-8f23-4852-9217-22994faa69c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='End-of-Year Clearance! Get extra 15% discount with code: EXTRA15']/parent::*</value>
      <webElementGuid>9d9e060b-3f3f-49bd-8f1a-467049e8e436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://homzmart.com/en/c/top-selling')]</value>
      <webElementGuid>f75db1eb-e298-4618-b506-8c6897e60a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>a8199708-820b-47c9-98c2-3252993d2f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://homzmart.com/en/c/top-selling' and (text() = 'End-of-Year Clearance! Get extra 15% discount with code: EXTRA15' or . = 'End-of-Year Clearance! Get extra 15% discount with code: EXTRA15')]</value>
      <webElementGuid>33ab9ec1-4e1a-48a6-8b55-d495b114db23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
