<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hi, qotbbbbbb.My Account</name>
   <tag></tag>
   <elementGuidId>797d64b9-31dc-45b0-baba-390fec79fbeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div[2]/div/div/div[4]/div[3]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiGrid-root.muiltr-7tzcdh > div.MuiGrid-root.muiltr-rfnosa > div.text-with-icon_textWithIcon__7_ffC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ed62afbe-ebde-41fd-9aa6-28ba0afcb78d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-with-icon_textWithIcon__7_ffC</value>
      <webElementGuid>c0705d48-4272-4971-8c39-56433f91755c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hi, qotbbbbbb...My Account</value>
      <webElementGuid>e7c935b0-1ca5-4e43-b1f5-d66a14a05d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;__className_818b7e&quot;]/div[@class=&quot;MuiGrid-root muiltr-1ij0jnt&quot;]/div[@class=&quot;MuiGrid-root styles_headerContainer__zvolI muiltr-rfnosa&quot;]/div[@class=&quot;base-header-wrapper_baseHeaderWrapper__Hlubz&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg base-container_baseContainer__W84Zx undefined muiltr-1qsxih2&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container HMZ_gap24 muiltr-1tsmbea&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item muiltr-1ucwsv6&quot;]/div[@class=&quot;MuiGrid-root desktop muiltr-rfnosa&quot;]/div[@class=&quot;MuiGrid-root muiltr-7tzcdh&quot;]/div[@class=&quot;MuiGrid-root muiltr-rfnosa&quot;]/div[@class=&quot;text-with-icon_textWithIcon__7_ffC&quot;]</value>
      <webElementGuid>7b0d1b30-f3ad-48bf-a6ea-736bebcd97ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[2]/div/div/div[4]/div[3]/div/div/div</value>
      <webElementGuid>a11c7f6f-1eb5-4abb-b741-6e7fd4f5de2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::div[11]</value>
      <webElementGuid>5b809b8c-7033-4084-a115-4821115379f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deliver to'])[1]/following::div[16]</value>
      <webElementGuid>c211dd61-434b-437f-a120-a91bbe30e08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Furniture'])[1]/preceding::div[9]</value>
      <webElementGuid>c5384391-9eab-4895-994e-a90d03065e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div/div</value>
      <webElementGuid>9c7cca18-b6da-4bda-bbe4-cbd5e0a7ea34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hi, qotbbbbbb...My Account' or . = 'Hi, qotbbbbbb...My Account')]</value>
      <webElementGuid>ab01beb7-a7ec-492b-b2c1-27ba91d9caac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
