<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Luma Bella Coffee Maker 4 Cups 250 ml 6_41a885</name>
   <tag></tag>
   <elementGuidId>c5a1b1b7-ba3f-4650-9348-eb67c81c3bfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div[5]/div/div[2]/div/div/div[2]/div/a/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.swiper-slide.swiper-slide-next > div.MuiGrid-root.base-productCard_productCard_container__JWX6i.muiltr-rfnosa > a > div.MuiGrid-root.base-productCard_productCard_content__Yg52w.muiltr-rfnosa > div.MuiGrid-root.base-productCard_maxHeight__DQB0A.muiltr-rfnosa</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>daa9be14-e5f2-426b-a319-869511a86890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiGrid-root base-productCard_maxHeight__DQB0A muiltr-rfnosa</value>
      <webElementGuid>e628ed6a-0ad6-4bbc-9461-4185fe8af796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Luma Bella Coffee Maker 4 Cups 250 ml 600 W Blue and Black - LB-54004EGP1,254.00EGP1,694.0026%OffOnly 10 left in stock</value>
      <webElementGuid>cb32d4ae-731e-484c-9e34-04180af8c871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;__className_818b7e&quot;]/main[1]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg base-container_baseContainerBody__PjcNt undefined muiltr-1qsxih2&quot;]/div[@class=&quot;HMZ_mg_b_20&quot;]/div[1]/div[@class=&quot;base-slider_sliderWrapper__2AaZ4&quot;]/div[@class=&quot;swiper swiper-initialized swiper-horizontal swiper-css-mode undefined false&quot;]/div[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide swiper-slide-next&quot;]/div[@class=&quot;MuiGrid-root base-productCard_productCard_container__JWX6i muiltr-rfnosa&quot;]/a[1]/div[@class=&quot;MuiGrid-root base-productCard_productCard_content__Yg52w muiltr-rfnosa&quot;]/div[@class=&quot;MuiGrid-root base-productCard_maxHeight__DQB0A muiltr-rfnosa&quot;]</value>
      <webElementGuid>48bbfc93-9617-4ad1-8f8b-23473ed7ed5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[5]/div/div[2]/div/div/div[2]/div/a/div[2]/div</value>
      <webElementGuid>91aa3985-26f2-4c86-8383-cb18ea84fa2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EGP'])[2]/following::div[9]</value>
      <webElementGuid>8e58afab-bc7d-4956-a454-3a8eaf3d0ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EGP'])[1]/following::div[12]</value>
      <webElementGuid>becd38a6-6c54-4f76-b37e-98478c1832dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/div[2]/div</value>
      <webElementGuid>47761b4b-c6d8-4711-b1b8-bfe3eed254ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Luma Bella Coffee Maker 4 Cups 250 ml 600 W Blue and Black - LB-54004EGP1,254.00EGP1,694.0026%OffOnly 10 left in stock' or . = 'Luma Bella Coffee Maker 4 Cups 250 ml 600 W Blue and Black - LB-54004EGP1,254.00EGP1,694.0026%OffOnly 10 left in stock')]</value>
      <webElementGuid>8b589388-e89d-4415-8841-aea4aa0766e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[5]/div/div[2]/div/div/div[2]/div/a/div[2]</value>
      <webElementGuid>9efb7467-fe6c-42dd-b19f-a778316352f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EGP'])[2]/following::div[8]</value>
      <webElementGuid>2e0e21ef-ab94-4c69-b4bc-b508089d43cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EGP'])[1]/following::div[11]</value>
      <webElementGuid>9292a7af-f30f-4b87-a3ae-c4af4aad2c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/a/div[2]</value>
      <webElementGuid>848c1bef-2647-4074-99e1-dc8cbef80545</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
