<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Alexandria_MuiBackdrop-root MuiBackdrop_30ee7a</name>
   <tag></tag>
   <elementGuidId>215bacf4-1b83-4015-9063-2bb23a439ecb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBackdrop-root.MuiBackdrop-invisible.MuiModal-backdrop.muiltr-esi9ax</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.MuiBackdrop-root >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d52a3fdd-c3dd-46f7-89f7-7f02cf12dcb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>17f7ed73-5325-4c9d-b973-4d8d413c01e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBackdrop-root MuiBackdrop-invisible MuiModal-backdrop muiltr-esi9ax</value>
      <webElementGuid>24b2fbce-eff2-4318-a9a9-55db06373eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiPopover-root MuiModal-root muiltr-jp7szo&quot;]/div[@class=&quot;MuiBackdrop-root MuiBackdrop-invisible MuiModal-backdrop muiltr-esi9ax&quot;]</value>
      <webElementGuid>c9e1ba19-0c0f-4cae-8854-1f2fa97e687c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>b149c910-dac4-4ea8-8c24-c0619074f717</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
