<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Steel and Marble Centre Table Gold and _4fecc4</name>
   <tag></tag>
   <elementGuidId>6950a058-127b-4d6b-9ede-55671f1df0b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div[3]/div/div/div/div/div[3]/div/div[2]/div[4]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d728c558-1681-4749-b773-ae6eb1abde87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Metal and Beech Wood Office Chair -</value>
      <webElementGuid>400c8201-f245-479f-a368-dbea2c73fe7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>c94e2882-ec2a-4f60-b078-2046373e225f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>b8f4bea2-2bcc-4a88-9a59-48ff6d701bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>9ac5bbca-ddae-408b-a2fb-01139bb4bdb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>41f2aca2-46e3-4c47-96c0-d6e42b0d523d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c8d237e9-2843-404c-90dd-4fb8b68fd468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>undefined </value>
      <webElementGuid>1ea6f905-2ab4-4852-b440-ff6473893330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://eg-rv.homzmart.net/catalog/product/d/h/dh_image_copy_.jpg</value>
      <webElementGuid>20b582ab-8a41-4886-acec-2ae069279ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;__className_818b7e&quot;]/main[1]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg base-container_baseContainerBody__PjcNt undefined muiltr-1qsxih2&quot;]/div[@class=&quot;HMZ_mg_b_20&quot;]/div[@class=&quot;MegaDeals_container__megaDeals__wsjRp&quot;]/div[@class=&quot;base-slider_sliderWrapper__2AaZ4&quot;]/div[@class=&quot;swiper swiper-initialized swiper-horizontal swiper-css-mode undefined false base-slider_removePadding__swCnz&quot;]/div[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide swiper-slide-next&quot;]/div[@class=&quot;MegaDealItems_megaDeals__0yX4J&quot;]/div[@class=&quot;MegaDealItems_wraperInfo__megaDeals__yY_cy&quot;]/div[@class=&quot;MegaDealSupItems_card__megaDeals__Fou0r&quot;]/div[@class=&quot;MegaDealSupItems_image__card__megaDeals__dZrH3&quot;]/a[1]/img[@class=&quot;undefined&quot;]</value>
      <webElementGuid>85cc9563-81ad-46fe-82a0-f3d493a0d3da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[3]/div/div/div/div/div[3]/div/div[2]/div[4]/div/a/img</value>
      <webElementGuid>4d7baf57-52db-499a-a330-25b87610edcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Metal and Beech Wood Office Chair -']</value>
      <webElementGuid>90494b42-4b80-47a0-8047-977d80932bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[4]/div/a/img</value>
      <webElementGuid>59dc551b-2fbe-4c95-be38-fc490bf1f2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Metal and Beech Wood Office Chair -' and @src = 'https://eg-rv.homzmart.net/catalog/product/d/h/dh_image_copy_.jpg']</value>
      <webElementGuid>20e3c02a-2daf-47e8-b7c9-0b5c6c0acd91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
