<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Steel and Marble Centre Table Gold and _4fecc4</name>
   <tag></tag>
   <elementGuidId>6950a058-127b-4d6b-9ede-55671f1df0b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div[3]/div/div/div/div/div[3]/div/div[2]/div[4]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b3b8c6fb-1693-4169-a413-4c42ac64f0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Metal and Beech Wood Office Chair -</value>
      <webElementGuid>5597d059-3516-46e5-ba90-5aacf17e5edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>5c087669-1c86-4daf-a076-e15b899b5cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>763de434-5817-43a9-9864-f6d1b3e3f35a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>3351027c-56b0-4e14-b105-19fd24a9e36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>4830c6f0-c508-4cfc-9338-5e879c20bcbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>da433f76-43f2-4e57-9f8c-ad06cd3d2c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>undefined </value>
      <webElementGuid>f62f6f1b-6bc6-43c0-9538-7d0b3867df1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://eg-rv.homzmart.net/catalog/product/d/h/dh_image_copy_.jpg</value>
      <webElementGuid>ce8656ed-a9fa-48f6-81cd-7e05dcff3e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;__className_818b7e&quot;]/main[1]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg base-container_baseContainerBody__PjcNt undefined muiltr-1qsxih2&quot;]/div[@class=&quot;HMZ_mg_b_20&quot;]/div[@class=&quot;MegaDeals_container__megaDeals__wsjRp&quot;]/div[@class=&quot;base-slider_sliderWrapper__2AaZ4&quot;]/div[@class=&quot;swiper swiper-initialized swiper-horizontal swiper-css-mode undefined false base-slider_removePadding__swCnz&quot;]/div[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide swiper-slide-next&quot;]/div[@class=&quot;MegaDealItems_megaDeals__0yX4J&quot;]/div[@class=&quot;MegaDealItems_wraperInfo__megaDeals__yY_cy&quot;]/div[@class=&quot;MegaDealSupItems_card__megaDeals__Fou0r&quot;]/div[@class=&quot;MegaDealSupItems_image__card__megaDeals__dZrH3&quot;]/a[1]/img[@class=&quot;undefined&quot;]</value>
      <webElementGuid>b8394b47-04eb-4f5d-918b-917031b5518c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[3]/div/div/div/div/div[3]/div/div[2]/div[4]/div/a/img</value>
      <webElementGuid>27abdee6-bde7-49a4-b6fc-f2eca7199ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Metal and Beech Wood Office Chair -']</value>
      <webElementGuid>3b35ec31-d45a-4b1d-80e5-0b5f192121cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[4]/div/a/img</value>
      <webElementGuid>7fb2e224-3aa9-465f-8723-b9df1577d3f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Metal and Beech Wood Office Chair -' and @src = 'https://eg-rv.homzmart.net/catalog/product/d/h/dh_image_copy_.jpg']</value>
      <webElementGuid>33ac44ef-e6ef-442f-b50b-6b363cada5df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
