<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_EGP_undefined</name>
   <tag></tag>
   <elementGuidId>496199aa-0fd7-42d7-9918-bb7df66e9d34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div[5]/div/div[2]/div/div/div[4]/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2d304f0e-7f69-40a1-9a39-642fed3379b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Gamma Bluetooth Sound Bar Speaker Heavy Bass Usb Sd Card Aux Black - GT -119</value>
      <webElementGuid>0cb7c378-3aa1-4ee9-82c6-b962fa57d8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>9b5e88b6-fe8e-474f-993a-c92beb03e44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>270</value>
      <webElementGuid>1ecddb0d-9e2a-49da-964f-f5c6f27832bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>270</value>
      <webElementGuid>9d632fcc-23e3-4531-bc8f-7f887f7c50a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>6d7bc0f8-51dc-4300-92f3-3589767b1635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>12b88b98-fefd-4414-aaa3-8bce67a5feb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>undefined </value>
      <webElementGuid>3d5c55df-2af3-4468-afd1-3aa1ff1a4b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://eg-rv.homzmart.net/catalog/product/n/s/ns14102027_-env.jpg</value>
      <webElementGuid>6f60559b-3791-41db-b8c7-18b4541890a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;__className_818b7e&quot;]/main[1]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg base-container_baseContainerBody__PjcNt undefined muiltr-1qsxih2&quot;]/div[@class=&quot;HMZ_mg_b_20&quot;]/div[1]/div[@class=&quot;base-slider_sliderWrapper__2AaZ4&quot;]/div[@class=&quot;swiper swiper-initialized swiper-horizontal swiper-css-mode undefined false&quot;]/div[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide&quot;]/div[@class=&quot;MuiGrid-root base-productCard_productCard_container__JWX6i muiltr-rfnosa&quot;]/a[1]/div[@class=&quot;MuiGrid-root base-productCard_productImageContainer__UCk92 muiltr-rfnosa&quot;]/img[@class=&quot;undefined&quot;]</value>
      <webElementGuid>8351f861-feb0-4283-a798-638610a4ab1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div[5]/div/div[2]/div/div/div[4]/div/a/div/img</value>
      <webElementGuid>fd0be4e8-0279-47a3-abfb-b3ca3a0a4ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Gamma Bluetooth Sound Bar Speaker Heavy Bass Usb Sd Card Aux Black - GT -119']</value>
      <webElementGuid>bb62d930-883a-4371-8101-938483414081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[4]/div/a/div/img</value>
      <webElementGuid>1f0d27f8-5a0a-4ea8-9401-adbc3cb36031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Gamma Bluetooth Sound Bar Speaker Heavy Bass Usb Sd Card Aux Black - GT -119' and @src = 'https://eg-rv.homzmart.net/catalog/product/n/s/ns14102027_-env.jpg']</value>
      <webElementGuid>2b888194-06e1-41fe-97a1-618faa3b18bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
