<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Shop By Category_undefined</name>
   <tag></tag>
   <elementGuidId>fffafbbe-16ae-4639-b06d-1fadc8cfd7f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Category Image 7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Category Image 7&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7b3357c3-dfeb-4194-b4c1-6e1bb1555e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Category Image 7</value>
      <webElementGuid>f185c12b-1c75-4642-b539-efd47f6a4f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>3f59d8a0-6dc9-4872-b83f-5441b8e017e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>dea56af1-9755-4ab1-89bc-a3fa7f43edee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>88</value>
      <webElementGuid>348fa1e2-cca5-4053-b647-4eb5b51f5133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>761fbfc4-7e6e-407b-9723-b18d2cd206e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b076f882-6d98-4992-ac25-6af7e07431d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>undefined </value>
      <webElementGuid>ba3693f8-965f-4c17-affd-84ebceb78bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://eg-rv.homzmart.net/menu/Frame+26787341.png</value>
      <webElementGuid>9c559d07-3835-4d45-8c15-8821c61945e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiDrawer-root MuiDrawer-modal MuiModal-root muiltr-y28f86&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation16 MuiDrawer-paper MuiDrawer-paperAnchorLeft styles_drawer__Xj4c_ muiltr-wf16b5&quot;]/div[@class=&quot;MuiGrid-root styles_mianContainerdefault__9LI67 muiltr-rfnosa&quot;]/div[@class=&quot;MuiGrid-root muiltr-rfnosa&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg muiltr-1qsxih2&quot;]/div[@class=&quot;MuiGrid-root muiltr-1twz3ee&quot;]/div[@class=&quot;MuiGrid-root muiltr-rfnosa&quot;]/div[@class=&quot;MuiGrid-root styles_catogreyContainer__R9AUI muiltr-rfnosa&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-md-12 styles_catogrey__R6MGZ muiltr-we0np1&quot;]/img[@class=&quot;undefined&quot;]</value>
      <webElementGuid>17d4bfe7-19e7-4e10-853e-5741ff5e3bc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Category Image 7']</value>
      <webElementGuid>4bf955f9-eae7-4938-8de0-7ecbe9a25bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[7]/img</value>
      <webElementGuid>814c4ca2-438d-4a78-a08a-ee621edd85a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Category Image 7' and @src = 'https://eg-rv.homzmart.net/menu/Frame+26787341.png']</value>
      <webElementGuid>58146230-c37f-458e-bdff-c09b25c70e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Category Image 4']</value>
      <webElementGuid>f95dbf2d-ba84-4e2d-951f-be35bcfef7b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/img</value>
      <webElementGuid>af5d35ed-5538-4f84-ab53-445d142886f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Category Image 4' and @src = 'https://eg-rv.homzmart.net/menu/Frame+26787346.png']</value>
      <webElementGuid>583735e0-1b90-44b9-b48a-a48dd22b5c89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
