<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Chairs</name>
   <tag></tag>
   <elementGuidId>fea8166c-f3c1-4fc2-944b-d447be45026e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='grouped-demo-option-1']/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#grouped-demo-option-1 > div.MuiGrid-root.muiltr-6ko5oj > p.base-typography_p__HIGSb.base-typography_small_reg__mVCqp.undefined.undefined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>21436789-c65d-411c-aa7e-32636bfa81b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-typography_p__HIGSb base-typography_small_reg__mVCqp undefined undefined</value>
      <webElementGuid>ea969746-823a-40ed-aa9b-704ba0c0d48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chairs</value>
      <webElementGuid>a96b589f-f483-402c-bca8-a76e2848d74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grouped-demo-option-1&quot;)/div[@class=&quot;MuiGrid-root muiltr-6ko5oj&quot;]/p[@class=&quot;base-typography_p__HIGSb base-typography_small_reg__mVCqp undefined undefined&quot;]</value>
      <webElementGuid>deca9196-7a0e-4b08-9ebd-a9f8db245a65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='grouped-demo-option-1']/div/p</value>
      <webElementGuid>901a18da-88ba-4e62-9232-08f900f5c37b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alexandria'])[1]/following::p[9]</value>
      <webElementGuid>33eac0e9-333f-4e46-b175-ba3c1943d316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mansoura,Dakahlia'])[1]/following::p[9]</value>
      <webElementGuid>bdb97e39-a755-4b76-b574-02e23848db04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Chairs']/parent::*</value>
      <webElementGuid>e8d58afd-b9bf-43b1-99fe-67e2f1f519d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/p</value>
      <webElementGuid>d65f6a63-17f9-4344-8870-325201502b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Chairs' or . = 'Chairs')]</value>
      <webElementGuid>46cd65f7-6ac5-4846-b4c5-1594e59c0194</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
