<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>7004b300-ba10-4d32-a3bb-1cd366a2bdc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div/ul/li[6]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;47&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;47&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4d421a12-5d65-4432-8924-84ce9125eb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>22d090b9-38e8-4930-8625-4cc0ae861b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>1db0780c-6bcd-4469-8fe2-c3989a603f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://fe-assets-testing-bucket.s3.eu-central-1.amazonaws.com/homzdesign-assets/img/brown_wood.jpg</value>
      <webElementGuid>31777c30-2caf-4811-9dff-a34ede02bd05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>47</value>
      <webElementGuid>f214f7d8-6979-4bd7-a6f2-fc18a9610bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://fe-assets-testing-bucket.s3.eu-central-1.amazonaws.com/homzdesign-assets/img/brown_wood.jpg</value>
      <webElementGuid>06d23fc2-51d9-4364-ae44-1451c54ed48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>152b4d12-1832-4389-b7b2-a651738f74d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-iGctyi kYhgmh&quot;]/main[@class=&quot;sc-irlPvL gIYSem&quot;]/div[@class=&quot;sc-iBPTVF kduQMP MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 sc-giInvV hbRzwi MuiCard-root sc-eWVLZl kJxplT&quot;]/ul[@class=&quot;sc-eJMOVy cArBfB MuiImageList-root MuiImageList-standard&quot;]/li[@class=&quot;sc-nFrIV kioDdK MuiImageListItem-root MuiImageListItem-standard&quot;]/div[@class=&quot;sc-iwyWfK eebLUH MuiBox-root&quot;]/img[1]</value>
      <webElementGuid>748f40f9-446c-4692-9fe9-8bf168efa43c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/ul/li[6]/div/img</value>
      <webElementGuid>8d6fb674-1f20-42c5-a4c5-0a2ffede88b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='47']</value>
      <webElementGuid>30a3b9c3-f8b3-457b-8fe7-061e90a073eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/img</value>
      <webElementGuid>bfd13f3e-cd1a-433c-94cc-7059726a57ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://fe-assets-testing-bucket.s3.eu-central-1.amazonaws.com/homzdesign-assets/img/brown_wood.jpg' and @alt = '47']</value>
      <webElementGuid>ed62ba41-f607-47ac-ad07-525519610f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/ul/li[3]/div/img</value>
      <webElementGuid>36f6e893-4b78-4a37-8d2f-0c4bdb1752f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='46']</value>
      <webElementGuid>add0e628-18e6-44a2-82e9-a378e36c18ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/img</value>
      <webElementGuid>08830880-cc37-4f07-93ef-60f22ca8874a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://fe-assets-testing-bucket.s3.eu-central-1.amazonaws.com/homzdesign-assets/img/hard_wood.jpg' and @alt = '46']</value>
      <webElementGuid>daccea0b-749f-4637-a3a9-0cd497c516d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
